name: "Docs Check"
on:
  pull_request:
  push:
    branches:
      - rolling
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '23 5 * * *'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: 'docs/'
        pre-build-command: "apt-get update -y && apt-get install -y python3-pip && pip3 install sphinx_rtd_theme"
